language: ruby
cache: bundler
env:
  - SERVER_IP_ADDRESS=31.31.196.115
branches:
  only:
  - master
install: gem install jekyll jekyll-sitemap
script:
- jekyll build --destination site
deploy:
  provider: pages
  local-dir: "./site"
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_83e622d86ec6_key -iv $encrypted_83e622d86ec6_iv
  -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./id_rsa
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./id_rsa
# test ssh connection for: https://github.com/dwyl/learn-travis/issues/42
- ssh -i ./id_rsa u0741843@31.31.196.115 pwd
